name: Lint & Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    name: ansible-lint / yamllint / syntax-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint
          ansible --version
          ansible-lint --version
          yamllint --version

      - name: Install required collections
        if: hashFiles('requirements.yml') != ''
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run ansible-lint
        run: ansible-lint -v

      - name: Run yamllint
        run: yamllint .

      - name: Syntax-check playbooks
        run: |
          set -e
          # Basic inventory to satisfy syntax-check if user forgets to pass -i
          mkdir -p inventories/ci && echo -e "[local]\nlocalhost ansible_connection=local" > inventories/ci/hosts.ini
          for p in $(find playbooks -maxdepth 1 -type f -name "*.yml" -o -name "*.yaml"); do
            echo ">>> Syntax checking $p"
            ansible-playbook -i inventories/ci/hosts.ini --syntax-check "$p"
          done
