*** a/.github/workflows/lint.yml
--- b/.github/workflows/lint.yml
@@
+---
 name: Lint
 on:
   push:
     branches: [ main ]
   pull_request:
-    branches: [ main ]
+    branches: [main]
 jobs:
   lint:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@
-      - name: Set up Python [ 3.11 ]
+      - name: Set up Python [3.11]
         uses: actions/setup-python@v5
         with:
           python-version: '3.11'
       - name: Install deps
         run: |
           python -m pip install --upgrade pip
           pip install ansible ansible-lint yamllint
       - name: Run ansible-lint
         run: ansible-lint -v
